# Dependencies
highlighter:   rouge   #pygments

gems: 
  - jekyll-paginate

# Permalinks
permalink:        pretty

# Setup
title:            Yanxiao Zhang
tagline:          'A Jekyll theme'
description:      'Bioinformatics PostDoc @Bing Ren Lab'
url:              http://shawnzhangyx.github.io
baseurl:          /

author:
  name:           'Yanxiao Zhang'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/shawnzhangyx/shawnzhangyx.github.io
