# Dependencies
highlighter:   rouge   #pygments

gems: 
  - jekyll-paginate

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Yanxiao Zhang
tagline:          'Too little time'
description:      'Bioinformatics PostDoc @Bing Ren Lab'
url:              https://shawnzhangyx.github.io
baseurl:          /

author:
  name:           'Yanxiao Zhang'
  url:            https://twitter.com/zhangyx.shawn

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/shawnzhangyx/shawnzhangyx.github.io
